### ISSUE TITLE
Support for USB device emulation

### ISSUE THREAD

**Issue by Martyx00** [madmachineio/SwiftIO#1]
Just a question that might not be relevant this early in the development stage, but do you plan to add support for emulating USB peripherals like Mass-storage and USB Proxy and program their behavior with custom Swift code? 

I am asking since it seems that the board has 2 separate USB connectors, relatively fast CPU and added benefit of Swift speed could make it ideal for this purpose as opposed to python.

**Comment by andy0808** [comment]
Thanks for your advice and sorry for this late reply.

USB is a very complex peripheral. SwiftIO board has only 1 usb conneted to the RT1052 chip(Another is connected to the debugger for debugging and serial communication).

It has the potential to provide USB stack to users, but now we have to make every ordinary peripheral work well. So this would be considered later!
