### ISSUE TITLE
Documentation for i2s

### ISSUE THREAD

**Issue by itzaks** [madmachineio/SwiftIO#2]
Hello!

Thanks for a great and beautiful project.

I see that there are headers added for i2s:
https://github.com/madmachineio/SwiftIO/blob/main/Sources/CSwiftIO/include/swift_i2s.h

But is it supported in the hardware for the board? Any documentation on how to use? Would be really cool :–)

Cheers,
Isak

**Comment by andy0808** [comment]
@itzaks we are going to update the I2S docs in recent days, stay tuned : )
