### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by lhoward** [madmachineio/SwiftIO#32]
s/swifthal_os_mq_destory/swifthal_os_mq_destroy/

s/eset/reset/ in `struct Semaphore`

**Comment by andy0808** [comment]
Fixed in branch [fix/minor_api_modify](https://github.com/madmachineio/SwiftIO/tree/fix/minor_api_modify)

Thank you for your kind reminder @lhoward 😊

**Comment by lhoward** [comment]
I know Linux building isn't a principal concern but, and I'm very appreciative of the type changes, but could you include `<stdint.h>` on the new branch?

```
Building for debugging...
While building module 'CSwiftIO' imported from /home/lukeh/CVSRoot/inferno/control/LinuxHalSwiftIO/Sources/LinuxHalSwiftIO/include/swift_hal.h:22:
In file included from <module-includes>:2:
/home/lukeh/CVSRoot/inferno/control/LinuxHalSwiftIO/.build/checkouts/SwiftIO/Sources/CSwiftIO/include/swift_adc.h:53:40: error: unknown type name 'uint16_t'
int swifthal_adc_read(const void *adc, uint16_t *sample_buffer);
                                       ^
...
```

**Comment by andy0808** [comment]
Got it and done!

It seems those definitions are located in different places in Newlib(which I use currently), macOS, and Linux. I think that's the reason I prefer to use *pure C type* when I first write this library 😂

**Comment by lhoward** [comment]
Thanks Andy! I've updated LinuxHalSwiftIO in a branch :)

I know you're probably not done with this yet, but a couple of comments:

* I'd use `ssize_t` for the return values of read and write functions, if they return the number of bytes read/written, for compatibility with 64-bit platforms
* `const void *` arguments don't always make sense for things that can mutate state (e.g. `swifthal_spi_config()`), although as `const` in C doesn't really mean it has to be const (you're free to cast it away), not a big deal
