### ISSUE TITLE
New Project fails to build with no changes

### ISSUE THREAD

**Issue by daltonclaybrook** [madmachineio/SwiftIO#42]
**Describe the bug**

New project build fails with no changes. The build log contains the following output:

```shell
.build/checkouts/SwiftIO/Sources/SwiftIO/Ethernet.swift:27:21: error: expected 'var' keyword in static property declaration
  static nonisolated(unsafe) var mac: [UInt8] = [UInt8](repeating: 0x00, count: 6)
                    ^
                    var 
.build/checkouts/SwiftIO/Sources/SwiftIO/Ethernet.swift:27:29: error: consecutive declarations on a line must be separated by ';'
  static nonisolated(unsafe) var mac: [UInt8] = [UInt8](repeating: 0x00, count: 6)
                            ^
                            ;
```

**To Reproduce**
1. Install the mm-sdk and the VSCode extension as described on the documentation website
2. Create a new project using VSCode as described on the website
3. Press "Build"

**Expected behavior**
The project should be built to the connected device

**Actual behavior**
The project fails to build with the errors above.

**Environment**
 - MM SDK version: 0.9.3
 - Hardware version: SwiftIOMicro

**Additional context**
I suspect this is happening because the mm-sdk uses its own bundled version of Swift, which is Swift 5.9.2

```shell
~/mm-sdk/usr/bin/swift-build --version
Swift Package Manager - Swift 5.9.2
```

and the generated project pulls from the SwiftIO main branch, which was recently updated with Swift 6 features, such as `nonisolated(unsafe)`

```swift
.package(url: "https://github.com/madmachineio/SwiftIO.git", branch: "main"),
```

**Comment by daltonclaybrook** [comment]
Is there a way to tell mm-sdk to use my system's installation of `swift-build` instead of the bundled version?

**Comment by andy0808** [comment]
Hi @daltonclaybrook 

I have just updated all the main repositories (SwiftIO, MadDrivers, MadExamples) to match the official Embedded Swift implementation based on the current nightly build.

You can now use the new [mm-sdk](https://github.com/madmachineio/mm-sdk/releases/tag/1.1.0-alpha.3) and follow the updated [instructions](https://docs.madmachine.io/overview/getting-started/software-prerequisite#3-setting-up-the-swift-development-enviroment) to build your code.
